# Generated by Django 4.0.5 on 2022-06-01 14:09

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('idkor', models.AutoField(db_column='IDKor', primary_key=True, serialize=False)),
                ('korisnickoime', models.CharField(blank=True, db_column='KorisnickoIme', default='0', max_length=20, unique=True)),
                ('ime', models.CharField(blank=True, db_column='Ime', default='0', max_length=20)),
                ('prezime', models.CharField(blank=True, db_column='Prezime', default='0', max_length=20)),
                ('email', models.CharField(blank=True, db_column='Email', default='0', max_length=20)),
                ('lozinka', models.CharField(blank=True, db_column='Lozinka', default='0', max_length=20)),
                ('jmbg', models.CharField(blank=True, db_column='JMBG', default='0', max_length=20, unique=True)),
                ('vip', models.IntegerField(blank=True, db_column='VIP', default=0)),
                ('kartica', models.CharField(blank=True, db_column='Kartica', default='0', max_length=20)),
                ('stanje', models.DecimalField(blank=True, db_column='Stanje', decimal_places=2, default=0, max_digits=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('idtik', models.AutoField(db_column='IDTik', primary_key=True, serialize=False)),
                ('datumuplate', models.DateField(blank=True, db_column='DatumUplate', null=True)),
                ('iznosuplate', models.DecimalField(blank=True, db_column='IznosUplate', decimal_places=2, max_digits=10, null=True)),
                ('kvota', models.DecimalField(blank=True, db_column='Kvota', decimal_places=2, max_digits=15, null=True)),
                ('dobitak', models.DecimalField(blank=True, db_column='Dobitak', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'tiket',
            },
        ),
        migrations.CreateModel(
            name='Utakmica',
            fields=[
                ('iduta', models.IntegerField(db_column='IDUta', primary_key=True, serialize=False)),
                ('datumpocetka', models.CharField(blank=True, db_column='DatumPocetka', max_length=18, null=True)),
                ('tim1', models.CharField(blank=True, db_column='Tim1', max_length=20, null=True)),
                ('tim2', models.CharField(blank=True, db_column='Tim2', max_length=20, null=True)),
            ],
            options={
                'db_table': 'utakmica',
            },
        ),
        migrations.CreateModel(
            name='Utakmica10',
            fields=[
                ('utakmica10', models.CharField(db_column='Utakmica10', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'utakmica10',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idkor', models.OneToOneField(db_column='IDKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Desetunizu',
            fields=[
                ('idkor', models.OneToOneField(db_column='IDKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('brojpogodaka', models.IntegerField(blank=True, db_column='BrojPogodaka', default=0)),
                ('odigrano', models.CharField(blank=True, db_column='Odigrano', default=0, max_length=20)),
                ('validno', models.IntegerField(blank=True, db_column='Validno', default=0)),
            ],
            options={
                'db_table': 'desetunizu',
            },
        ),
        migrations.CreateModel(
            name='Igrac',
            fields=[
                ('idkor', models.OneToOneField(db_column='IDKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'igrac',
            },
        ),
        migrations.CreateModel(
            name='Kvoter',
            fields=[
                ('idkor', models.OneToOneField(db_column='IDKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kvoter',
            },
        ),
        migrations.CreateModel(
            name='Odigrano10Unizu',
            fields=[
                ('idkor', models.OneToOneField(db_column='IDKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ishod', models.IntegerField(db_column='Ishod')),
            ],
            options={
                'db_table': 'odigrano10unizu',
            },
        ),
        migrations.CreateModel(
            name='Utakmiceunajavi',
            fields=[
                ('iduta', models.OneToOneField(db_column='IDUta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='igrac.utakmica')),
            ],
            options={
                'db_table': 'utakmiceunajavi',
            },
        ),
        migrations.CreateModel(
            name='Zavrseneutakmice',
            fields=[
                ('iduta', models.OneToOneField(db_column='IDUta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='igrac.utakmica')),
                ('ishod', models.IntegerField(db_column='Ishod')),
                ('poluvremekraj', models.CharField(db_column='PoluvremeKraj', max_length=3)),
                ('prvigol', models.CharField(db_column='PrviGol', max_length=1)),
            ],
            options={
                'db_table': 'zavrseneutakmice',
            },
        ),
        migrations.CreateModel(
            name='Tiketdogadjaj',
            fields=[
                ('iddog', models.AutoField(db_column='IDDog', primary_key=True, serialize=False)),
                ('odigrano', models.CharField(blank=True, db_column='Odigrano', max_length=20, null=True)),
                ('kvota', models.DecimalField(db_column='Kvota', decimal_places=2, max_digits=15)),
                ('ishod', models.IntegerField(blank=True, db_column='Ishod', null=True)),
                ('idtik', models.ForeignKey(db_column='IDTik', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='igrac.tiket')),
                ('iduta', models.ForeignKey(db_column='IDUta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='igrac.utakmica')),
            ],
            options={
                'db_table': 'tiketdogadjaj',
            },
        ),
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('idsta', models.AutoField(db_column='IDSta', primary_key=True, serialize=False)),
                ('brojpogodjenih', models.IntegerField(blank=True, db_column='BrojPogodjenih', default=0)),
                ('brojpromasenih', models.IntegerField(blank=True, db_column='BrojPromasenih', default=0)),
                ('brojprimljenihpogodjenih', models.IntegerField(blank=True, db_column='BrojPrimljenihPogodjenih', default=0)),
                ('brojprimljenihpromasenih', models.IntegerField(blank=True, db_column='BrojPrimljenihPromasenih', default=0)),
                ('ukupnouplaceno', models.DecimalField(blank=True, db_column='UkupnoUplaceno', decimal_places=2, default=0, max_digits=15)),
                ('ukupnodobijeno', models.DecimalField(blank=True, db_column='UkupnoDobijeno', decimal_places=2, default=0, max_digits=15)),
                ('idkor', models.ForeignKey(db_column='IDKor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'statistika',
            },
        ),
        migrations.CreateModel(
            name='Istorijautakmica',
            fields=[
                ('idis', models.AutoField(db_column='IDIs', primary_key=True, serialize=False)),
                ('odigrano', models.CharField(blank=True, db_column='Odigrano', max_length=100, null=True)),
                ('ishod', models.IntegerField(blank=True, db_column='Ishod', null=True)),
                ('idkor', models.ForeignKey(db_column='IDKor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'istorijautakmica',
            },
        ),
        migrations.CreateModel(
            name='Viptiket',
            fields=[
                ('idvip', models.AutoField(db_column='IDVip', primary_key=True, serialize=False)),
                ('datumuplate', models.DateField(blank=True, db_column='DatumUplate', null=True)),
                ('iznosuplate', models.DecimalField(blank=True, db_column='IznosUplate', decimal_places=2, max_digits=10, null=True)),
                ('kvota', models.DecimalField(blank=True, db_column='Kvota', decimal_places=2, max_digits=15, null=True)),
                ('dobitak', models.DecimalField(blank=True, db_column='Dobitak', decimal_places=2, max_digits=15, null=True)),
                ('odigrano', models.CharField(blank=True, db_column='Odigrano', max_length=20, null=True)),
                ('idtik', models.ForeignKey(blank=True, db_column='IDTik', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='igrac.tiket')),
                ('idkor', models.ForeignKey(blank=True, db_column='IDKor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='igrac.igrac')),
                ('idkvo', models.ForeignKey(blank=True, db_column='IDKvo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='igrac.kvoter')),
            ],
            options={
                'db_table': 'viptiket',
            },
        ),
        migrations.CreateModel(
            name='Vipkvote',
            fields=[
                ('idkvo', models.AutoField(db_column='IDKvo', primary_key=True, serialize=False)),
                ('kvotaprolaz', models.DecimalField(blank=True, db_column='KvotaProlaz', decimal_places=2, max_digits=5, null=True)),
                ('kvotapad', models.DecimalField(blank=True, db_column='KvotaPad', decimal_places=2, max_digits=5, null=True)),
                ('idtik', models.ForeignKey(blank=True, db_column='IDTik', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='igrac.tiket')),
                ('idkor', models.ForeignKey(blank=True, db_column='IDKor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='igrac.kvoter')),
            ],
            options={
                'db_table': 'vipkvote',
            },
        ),
        migrations.AddField(
            model_name='tiket',
            name='idkor',
            field=models.ForeignKey(blank=True, db_column='IDKor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='igrac.igrac'),
        ),
        migrations.AddField(
            model_name='tiket',
            name='idkvo',
            field=models.ForeignKey(blank=True, db_column='IDKvo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='igrac.kvoter'),
        ),
        migrations.CreateModel(
            name='Postavljenekvote',
            fields=[
                ('idkvo', models.CharField(db_column='IDKvo', max_length=18, primary_key=True, serialize=False)),
                ('kvota1', models.DecimalField(blank=True, db_column='Kvota1', decimal_places=2, max_digits=5, null=True)),
                ('kvotax', models.DecimalField(blank=True, db_column='KvotaX', decimal_places=2, max_digits=5, null=True)),
                ('kvota2', models.DecimalField(blank=True, db_column='Kvota2', decimal_places=2, max_digits=5, null=True)),
                ('kvota11', models.DecimalField(blank=True, db_column='Kvota11', decimal_places=2, max_digits=5, null=True)),
                ('kvota1x', models.DecimalField(blank=True, db_column='Kvota1X', decimal_places=2, max_digits=5, null=True)),
                ('kvota12', models.DecimalField(blank=True, db_column='Kvota12', decimal_places=2, max_digits=5, null=True)),
                ('kvotax1', models.DecimalField(blank=True, db_column='KvotaX1', decimal_places=2, max_digits=5, null=True)),
                ('kvotaxx', models.DecimalField(blank=True, db_column='KvotaXX', decimal_places=2, max_digits=5, null=True)),
                ('kvotax2', models.DecimalField(blank=True, db_column='KvotaX2', decimal_places=2, max_digits=5, null=True)),
                ('kvota21', models.DecimalField(blank=True, db_column='Kvota21', decimal_places=2, max_digits=5, null=True)),
                ('kvota2x', models.DecimalField(blank=True, db_column='Kvota2X', decimal_places=2, max_digits=5, null=True)),
                ('kvota22', models.DecimalField(blank=True, db_column='Kvota22', decimal_places=2, max_digits=5, null=True)),
                ('prvigol1', models.DecimalField(blank=True, db_column='PrviGol1', decimal_places=2, max_digits=5, null=True)),
                ('prvigol2', models.DecimalField(blank=True, db_column='PrviGol2', decimal_places=2, max_digits=5, null=True)),
                ('prvigol3', models.DecimalField(blank=True, db_column='PrviGol3', decimal_places=2, max_digits=5, null=True)),
                ('iduta', models.ForeignKey(blank=True, db_column='IDUta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='igrac.utakmica')),
                ('idkor', models.ForeignKey(blank=True, db_column='IDKor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='igrac.kvoter')),
            ],
            options={
                'db_table': 'postavljenekvote',
            },
        ),
    ]
